Feature/enhancement 1
joselrodrigues/ghibliApp pull request #1
Opened 2021-03-13 23:49 UTC by joselrodrigues

All the skeleton configuration needed for start react with typescript proyect

2021-03-18 20:25 UTC, calarconpieriz requested changes
Un par de comentarios. Por lo demás está todo bien.

2021-03-18 21:05 UTC, joselrodrigues commented on package.json
> +    "react-app-rewired": "^2.1.8"
Ok me podrias decir especificamente cual babel (@babel/preset-react)?? y si pudieras darme mas contexto de porque instalar babel? estaría genial. Lo pregunto porque he leido que por debajo de CRA cli tiene webpack y tiene babel, porfa corrigeme si no es así y demas entender porque 👍

2021-03-18 21:06 UTC, joselrodrigues commented on config-overrides.js
> +const {alias, aliasJest, configPaths} = require('react-app-rewire-alias')
perfect voy a configurar mi prettier para que haga espacio en los brackets

2021-03-18 21:06 UTC, joselrodrigues commented on src/actions/films.actions.tsx
> +import {ALL_FILMS} from "@actions/constants";
Perfecto!

2021-03-18 21:09 UTC, joselrodrigues commented on src/atoms/.gitignore
> +# Ignore everything in this directory
Este no es un archivo del editor lo que hice fue un truco para poder subir una carpeta vacía para poder completar el atomic desing que consiste básicamente en 4 carpetas atoms molecules organisms pages y templates pero como algunas no podía subirlas porque no tienen nada y git no sube carpetas vacías le puse el trucaso del gitignore pero si lo deseas lo quito

2021-03-18 21:30 UTC, joselrodrigues commented on config-overrides.js
> +const {alias, aliasJest, configPaths} = require('react-app-rewire-alias')
Fué corregido en el commit [6731203d84537b4170481602641921d9d5326e24](https://github.com/joselrodrigues/ghibliApp/pull/1/commits/6731203d84537b4170481602641921d9d5326e24)

2021-03-18 21:31 UTC, joselrodrigues commented on src/actions/films.actions.tsx
> +import {ALL_FILMS} from "@actions/constants";
Fué corregido en el commit [6731203d84537b4170481602641921d9d5326e24](https://github.com/joselrodrigues/ghibliApp/pull/1/commits/6731203d84537b4170481602641921d9d5326e24)

2021-03-18 21:32 UTC, joselrodrigues commented on package.json
> +    "react-app-rewired": "^2.1.8"
Probablemente quizás también sea bueno incluir [husky](https://www.npmjs.com/package/husky) para los commit y así de una vez me ayuda porque voy a necesitar implementar esa librería en el proyecto que llevo ahorita

2021-03-23 15:06 UTC, calarconpieriz commented on package.json
> +    "react-app-rewired": "^2.1.8"
Olvida lo de Babel. Mala mia. Este proyecto tiene TypeScript y no es necesario.

2021-03-23 15:07 UTC, calarconpieriz approved these changes
LGTM

2021-03-23 22:37 UTC, merged